jobs:
- name: hello-secret
  plan:
  - task: divulge-secret
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      params:
        secret: ((secret))
      run:
        path: sh
        args:
        - -exc
        - | 
          echo "The secret is [$secret]."

